name: 复制Clash节点文件

on: 
  push:
    branches:
      - main # 监听主分支的推送事件

  schedule:
    - cron: '0 * * * *' # 每小时执行一次，可以根据需求调整时间
   
jobs:
  copy_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        run: curl -LO https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash

      - name: Create node directory if not exists
        run: mkdir -p $GITHUB_WORKSPACE/node

      - name: Move file to node directory
        run: mv clash $GITHUB_WORKSPACE/node/
