name: 复制Clash节点文件

on: 
  push:
    branches:
      - main # 监听主分支的推送事件
      
jobs:
  copy_file:
    runs-on: ubuntu-latest
    steps:
      - name: 下载文件
        run: |
          wget -O clash https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash

      - name: 构建目录
        run: mkdir -p node/clash
        
      - name: 复制文件
        run: cp clash node/clash

      - name: 配置Git
        run: |
          git config --global user.name "QingYi-Studio"
          git config --global user.email "qingyi.studio@gmail.com"

      - name: 提交改动
        run: |
          git add .
          git commit -m "Copy file from internet"
          git push origin main

      - name: 推送改动
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.Admin }}
          branch: main
