name: 复制Clash节点文件

on: 
  push:
    branches:
      - main # 监听主分支的推送事件

  schedule:
    - cron: '0 * * * *' # 每小时执行一次，可以根据需求调整时间
   
jobs:
  copy_file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download file
        run: curl -LO https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash  # 替换为要复制的文件的 URL

      - name: Move file
        run: mv clash ./node/  # 将文件移动到根目录下的node文件夹中
